services:
  bot-contabilidad:
    build: .
    container_name: bot-contabilidad
    restart: unless-stopped
    ports:
      - 8000
    volumes:
      - /home/debian/secrets:/app/secrets
    environment:
      - EVOLUTION_API_BASE_URL=${EVOLUTION_API_BASE_URL}
      - EVOLUTION_API_INSTANCE_NAME=${EVOLUTION_API_INSTANCE_NAME}
      - EVOLUTION_API_TOKEN=${EVOLUTION_API_TOKEN}
      - WHISPER_URL=${WHISPER_URL}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - MASTER_FOLDER_ID=${MASTER_FOLDER_ID}
      - PLANILLA_TEMPLATE_ID=${PLANILLA_TEMPLATE_ID}
      - GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI}
      - GOOGLE_CLIENT_SECRET_PATH=${GOOGLE_CLIENT_SECRET_PATH}
      - GOOGLE_TOKEN_PATH=${GOOGLE_TOKEN_PATH}
      - DATABASE_PATH=${DATABASE_PATH}
      - DATABASE_SCHEMA_PATH=${DATABASE_SCHEMA_PATH}
    networks:
      - pan-de-oro

networks:
  pan-de-oro:
    external: true
